# Coordina los 2 contenedores en orden
services:

  # Contenedor 1: descarga y limpia los datos
  data-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - data-volume:/app/data
    env_file:
      - .env

  # Contenedor 2: la app de Streamlit
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - data-volume:/app/data
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - data-pipeline

# Volumen compartido donde se pasan los datos entre contenedores
volumes:
  data-volume:
